/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dyantec.gui.acesso;

import br.com.dyantec.gui.mensalista.JfrmPagamentoMensalista;
import br.com.dyantec.gui.movimentoCaixa.JFrameMovimentoCaixa;
import br.com.dyantec.util.Parametros;
import br.com.dyantec.util.Util;
import br.com.dynatec.controlador.ws.RetornaTabelasHelperVO;
import br.com.dynatec.controlador.ws.RetornoConsultaCartaoVO;
import br.com.dynatec.controlador.ws.Tabela;
import br.com.dynatec.controlador.ws.TipoMovimento;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jura
 */
public class jfrmAcesso extends javax.swing.JFrame implements Observer {

    private Integer usuarioId;
    private String usuarioNome;
    private Date dataTransacaoFinanceira;

    /**
     * Creates new form jfrmAcesso
     */
    public jfrmAcesso() {
        initComponents();
        populaJCombobox();
        startRelogio();
        this.setDataTransacaoFinanceira(new Date());

//        jbtnConsultar.setMnemonic(java.awt.event.KeyEvent.VK_F1);
//        Util.addHotKey(this, jbtnConsultar, KeyEvent.VK_F1);
//        Util.addHotKey(this, jbtnConfirmar, KeyEvent.VK_F5);
//        Util.addHotKey(this, jbtnImprimir, KeyEvent.VK_F8);
        txtCartao.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTabelas = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPlacaVeiculo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        jbtnConsultar = new javax.swing.JToggleButton();
        jbtnImprimir = new javax.swing.JToggleButton();
        lblRelogio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cupom = new javax.swing.JTextPane();
        btnDepositoCaixa = new javax.swing.JButton();
        btnDepositoCaixa3 = new javax.swing.JButton();
        btnDepositoCaixa2 = new javax.swing.JButton();
        btnDepositoCaixa1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnConfirmar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jlblValorReceber = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlblTroco = new javax.swing.JLabel();
        jlblPermanencia = new javax.swing.JLabel();
        jlblTempoDisponivel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Acesso");

        jLabel1.setText("Tabela:");

        jComboBoxTabelas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel2.setText("Cartão:");

        txtCartao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCartaoActionPerformed(evt);
            }
        });
        txtCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCartaoKeyPressed(evt);
            }
        });

        jLabel5.setText("Placa do veículo:");

        txtPlacaVeiculo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel4.setText("Valor recebido:");

        txtValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,###.00"))));
        txtValorRecebido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtValorRecebido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorRecebidoKeyPressed(evt);
            }
        });

        jLabel3.setText("Desconto:");

        txtDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,###.00"))));
        txtDesconto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescontoKeyPressed(evt);
            }
        });

        jbtnConsultar.setText("Consultar - F1");
        jbtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarActionPerformed(evt);
            }
        });

        jbtnImprimir.setText("Imprimir - F8");
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });

        lblRelogio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRelogio.setText("25/12/1919 00:00:00");
        lblRelogio.setToolTipText("");
        lblRelogio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cupom.setContentType("text/html"); // NOI18N
        cupom.setText("");
        jScrollPane1.setViewportView(cupom);

        btnDepositoCaixa.setText("Deposito de Caixa");
        btnDepositoCaixa.setToolTipText("");
        btnDepositoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoCaixaActionPerformed(evt);
            }
        });

        btnDepositoCaixa3.setText("Perda de Cartão");
        btnDepositoCaixa3.setToolTipText("");
        btnDepositoCaixa3.setEnabled(false);

        btnDepositoCaixa2.setText("Retirada de Caixa");
        btnDepositoCaixa2.setToolTipText("");
        btnDepositoCaixa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoCaixa2ActionPerformed(evt);
            }
        });

        btnDepositoCaixa1.setText("Mensalista");
        btnDepositoCaixa1.setToolTipText("");
        btnDepositoCaixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositoCaixa1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Permanência:");

        jLabel7.setText("Tempo disponivel:");

        jbtnConfirmar.setText("Confirmar - F5");
        jbtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarActionPerformed(evt);
            }
        });

        jbtnSair.setText("Sair - ESC");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });

        jLabel9.setText("Valor a receber:");

        jlblValorReceber.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblValorReceber.setText("R$ 0.00");

        jLabel10.setText("Troco:");

        jlblTroco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblTroco.setText("R$ 0.00");

        jlblPermanencia.setText("00:00");

        jlblTempoDisponivel.setText("00:00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDepositoCaixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositoCaixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDepositoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTempoDisponivel)
                            .addComponent(jlblPermanencia)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlblTroco)
                                .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlblValorReceber)
                                .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbtnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnConfirmar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblRelogio, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRelogio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTabelas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblValorReceber)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jlblTroco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnImprimir)
                            .addComponent(jbtnConsultar)
                            .addComponent(jbtnConfirmar))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlblPermanencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTempoDisponivel)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDepositoCaixa2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositoCaixa3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDepositoCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxTabelas, txtCartao, txtDesconto, txtPlacaVeiculo, txtValorRecebido});

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Controle de Estacionamento");

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/jura/projetos/estacionamento/image001.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        try {
            cupom.print(new MessageFormat("Header"), new MessageFormat("Footer"), true, null, null, true);
        } catch (PrinterException ex) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void jbtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarActionPerformed
        consultarCartao();
    }//GEN-LAST:event_jbtnConsultarActionPerformed

    private void jbtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarActionPerformed
        //java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela
        String cartao = txtCartao.getText();
        Tabela tabela = (Tabela) jComboBoxTabelas.getSelectedItem();
        String dataTransacao = Util.dateToString(new Date());

        Double desconto = "".equals(txtDesconto.getText()) ? 0.0 : Double.valueOf(txtDesconto.getText().replace(".", "").replace(",", "."));
        Double valorRecebido = "".equals(txtValorRecebido.getText()) ? 0.0 : Double.valueOf(txtValorRecebido.getText().replace(".", "").replace(",", "."));
        String placaCarro = txtPlacaVeiculo.getText();

        RetornoConsultaCartaoVO consulta = processaCartao(cartao, dataTransacao, tabela.getId(), desconto, valorRecebido, this.getUsuarioId(), placaCarro);

        cupom.setText(Util.cupom(consulta).toString());
        atualizarValoresTela(consulta);
    }//GEN-LAST:event_jbtnConfirmarActionPerformed

    private void btnDepositoCaixa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoCaixa2ActionPerformed
        JFrameMovimentoCaixa frmMovimentoCaixa = new JFrameMovimentoCaixa();
        frmMovimentoCaixa.setLocationRelativeTo(null);
        frmMovimentoCaixa.setIdUsuario(this.getUsuarioId());
        frmMovimentoCaixa.setTipoMovimento(TipoMovimento.RETIRADA);
        frmMovimentoCaixa.setDataTransacaoFinanceira(this.getDataTransacaoFinanceira());
        frmMovimentoCaixa.atualizaVisualizacao();
        frmMovimentoCaixa.setVisible(true);
    }//GEN-LAST:event_btnDepositoCaixa2ActionPerformed

    private void btnDepositoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoCaixaActionPerformed
        JFrameMovimentoCaixa frmMovimentoCaixa = new JFrameMovimentoCaixa();
        frmMovimentoCaixa.setLocationRelativeTo(null);
        frmMovimentoCaixa.setIdUsuario(this.getUsuarioId());
        frmMovimentoCaixa.setTipoMovimento(TipoMovimento.DEPOSITO);
        frmMovimentoCaixa.setDataTransacaoFinanceira(this.getDataTransacaoFinanceira());
        frmMovimentoCaixa.atualizaVisualizacao();
        frmMovimentoCaixa.setVisible(true);
    }//GEN-LAST:event_btnDepositoCaixaActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void btnDepositoCaixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoCaixa1ActionPerformed
        // TODO add your handling code here:
        JfrmPagamentoMensalista frmMensalista = new JfrmPagamentoMensalista();
        frmMensalista.setLocationRelativeTo(null);
        frmMensalista.setIdUsuario(this.getUsuarioId());
        frmMensalista.setDataTransacaoFinanceira(this.getDataTransacaoFinanceira());
        frmMensalista.atualizaVisualizacao();
        frmMensalista.setVisible(true);
    }//GEN-LAST:event_btnDepositoCaixa1ActionPerformed

    private void txtCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartaoActionPerformed

    private void txtCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            consultarCartao();
            txtDesconto.requestFocus();
        }
    }//GEN-LAST:event_txtCartaoKeyPressed

    private void txtDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtValorRecebido.requestFocus();
        }
    }//GEN-LAST:event_txtDescontoKeyPressed

    private void txtValorRecebidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorRecebidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPlacaVeiculo.requestFocus();
        }
    }//GEN-LAST:event_txtValorRecebidoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmAcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAcesso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositoCaixa;
    private javax.swing.JButton btnDepositoCaixa1;
    private javax.swing.JButton btnDepositoCaixa2;
    private javax.swing.JButton btnDepositoCaixa3;
    private javax.swing.JTextPane cupom;
    private javax.swing.JComboBox jComboBoxTabelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnConfirmar;
    private javax.swing.JToggleButton jbtnConsultar;
    private javax.swing.JToggleButton jbtnImprimir;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JLabel jlblPermanencia;
    private javax.swing.JLabel jlblTempoDisponivel;
    private javax.swing.JLabel jlblTroco;
    private javax.swing.JLabel jlblValorReceber;
    private javax.swing.JLabel lblRelogio;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JTextField txtPlacaVeiculo;
    private javax.swing.JFormattedTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables

    public void populaJCombobox() {
        RetornaTabelasHelperVO retorno = recuperaTabelas_1();

        for (Tabela tabela : retorno.getTabelas()) {
            jComboBoxTabelas.addItem(tabela);
        }
    }

    public void consultarCartao() {
        String cartao = txtCartao.getText();
        Tabela tabela = (Tabela) jComboBoxTabelas.getSelectedItem();
        String dataTransacao = Util.dateToString(new Date());

        Double desconto = "".equals(txtDesconto.getText()) ? 0.0 : Double.valueOf(txtDesconto.getText().replace(".", "").replace(",", "."));
        Double valorRecebido = "".equals(txtValorRecebido.getText()) ? 0.0 : Double.valueOf(txtValorRecebido.getText().replace(".", "").replace(",", "."));
        String placaCarro = txtPlacaVeiculo.getText();

        RetornoConsultaCartaoVO consulta = consultaCartao(cartao, dataTransacao, tabela.getId(), desconto, valorRecebido, this.getUsuarioId(), placaCarro);

        cupom.setText(Util.cupom(consulta).toString());
        atualizarValoresTela(consulta);
    }

    public void atualizarValoresTela(RetornoConsultaCartaoVO acesso) {
        jlblPermanencia.setText(acesso.getPermanencia());

        jlblTempoDisponivel.setText(String.valueOf(acesso.getLimiteParaSairEmMinutos()));
        jlblTroco.setText("R$ " + String.valueOf(acesso.getTroco()));
        jlblValorReceber.setText("R$ " + String.valueOf(acesso.getValorReceber()));
    }

    private static RetornaTabelasHelperVO recuperaTabelas_1() {
        br.com.dynatec.controlador.ws.AcessoControle_Service service = new br.com.dynatec.controlador.ws.AcessoControle_Service();
        br.com.dynatec.controlador.ws.AcessoControle port = service.getAcessoControlePort();
        return port.recuperaTabelas();
    }

    private void startRelogio() {
        new Thread(new Relogio(this)).start();
    }

    @Override
    public void update(Observable o, Object arg) {
        Relogio time = (Relogio) o;
        this.lblRelogio.setText(time.getHoras());
    }

    public Integer getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    public String getUsuarioNome() {
        return usuarioNome;
    }

    public void setUsuarioNome(String usuarioNome) {
        this.usuarioNome = usuarioNome;
    }

    public Date getDataTransacaoFinanceira() {
        return dataTransacaoFinanceira;
    }

    public void setDataTransacaoFinanceira(Date dataTransacaoFinanceira) {
        this.dataTransacaoFinanceira = dataTransacaoFinanceira;
    }

    private static RetornoConsultaCartaoVO processaCartao(java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela, java.lang.Double desconto, java.lang.Double valorRecebido, java.lang.Integer usuarioId, java.lang.String placaCarro) {
        br.com.dynatec.controlador.ws.AcessoControle_Service service = new br.com.dynatec.controlador.ws.AcessoControle_Service(Parametros.WSDL_WEBSERVICE);

        br.com.dynatec.controlador.ws.AcessoControle port = service.getAcessoControlePort();
        return port.processaCartao(cartao, dataTransasaoFinanceira, codTabela, desconto, valorRecebido, usuarioId, placaCarro);
    }

    private static RetornoConsultaCartaoVO consultaCartao(java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela, java.lang.Double desconto, java.lang.Double valorRecebido, java.lang.Integer usuarioId, java.lang.String placaCarro) {
        br.com.dynatec.controlador.ws.AcessoControle_Service service = new br.com.dynatec.controlador.ws.AcessoControle_Service(Parametros.WSDL_WEBSERVICE);
        br.com.dynatec.controlador.ws.AcessoControle port = service.getAcessoControlePort();
        return port.consultaCartao(cartao, dataTransasaoFinanceira, codTabela, desconto, valorRecebido, usuarioId, placaCarro);
    }

}
