/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.dyantec.gui.mensalista;

import br.com.dyantec.type.TipoImpressao;
import br.com.dyantec.util.Impressora;
import br.com.dyantec.util.Parametros;
import br.com.dyantec.util.Util;
import br.com.dynatec.controlador.ws.RetornoConsultaCartaoVO;
import java.awt.print.PrinterException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jura
 */
public class JfrmPagamentoMensalista extends javax.swing.JFrame {

    private Date dataTransacaoFinanceira;
    private Integer idUsuario;
    private RetornoConsultaCartaoVO consulta;

    /**
     * Creates new form JfrmPagamentoMensalista
     */
    public JfrmPagamentoMensalista() {
        initComponents();
        txtCartao.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCartao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtValorRecebido = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JFormattedTextField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jbtnImprimir = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cupom = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jbtnConfirmar = new javax.swing.JButton();
        jlblValorMensalidade = new javax.swing.JLabel();
        jlblTroco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlblNomeMensalista = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jlblCPF = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mensalista - Pagamento Mensalidade");
        setResizable(false);

        jLabel2.setText("Cartão:");

        txtCartao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel5.setText("Troco:");

        jLabel4.setText("Valor recebido:");

        txtValorRecebido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,###.00"))));
        txtValorRecebido.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setText("Desconto:");

        txtDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###,###.00"))));
        txtDesconto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jToggleButton2.setText("Consultar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jbtnImprimir.setText("Imprimir");
        jbtnImprimir.setEnabled(false);
        jbtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirActionPerformed(evt);
            }
        });

        cupom.setContentType("text/html"); // NOI18N
        cupom.setText("");
        jScrollPane1.setViewportView(cupom);

        jLabel6.setText("Valor da mensalidade:");

        jbtnConfirmar.setText("Confirmar");
        jbtnConfirmar.setEnabled(false);
        jbtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfirmarActionPerformed(evt);
            }
        });

        jlblValorMensalidade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblValorMensalidade.setText("R$ 0,00");

        jlblTroco.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlblTroco.setText("R$ 0,00");

        jLabel7.setText("Nome do mensalista:");

        jlblNomeMensalista.setText("Nome");

        jLabel9.setText("CPF:");

        jlblCPF.setText("CPF");

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCartao)
                                    .addComponent(txtDesconto)
                                    .addComponent(txtValorRecebido)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblValorMensalidade)
                                            .addComponent(jlblTroco))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblNomeMensalista)
                                    .addComponent(jlblCPF))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jlblValorMensalidade))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jlblTroco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnImprimir)
                            .addComponent(jToggleButton2)
                            .addComponent(jbtnConfirmar)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jlblNomeMensalista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jlblCPF)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/jura/projetos/estacionamento/image001.png")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setText("Pagamento Mensalista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfirmarActionPerformed
        //java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela
        String cartao = txtCartao.getText();
        String dataTransacao = Util.dateToString(this.getDataTransacaoFinanceira());

        Double desconto = "".equals(txtDesconto.getText()) ? 0.0 : Double.valueOf(txtDesconto.getText().replace(".", "").replace(",", "."));
        Double valorRecebido = "".equals(txtValorRecebido.getText()) ? 0.0 : Double.valueOf(txtValorRecebido.getText().replace(".", "").replace(",", "."));

        consulta = processaCartao(cartao, dataTransacao, null, desconto, valorRecebido, this.getIdUsuario(), null);

        JOptionPane.showMessageDialog(null, consulta.getMensagem());

        jbtnImprimir.setEnabled("ok".equals(consulta.getStatus()));
        jbtnConfirmar.setEnabled(!"ok".equals(consulta.getStatus()));

        cupom.setText(Util.cupom(consulta, TipoImpressao.HTML).toString());
        
        atualizarValoresTela();

        txtCartao.setText("");
    }//GEN-LAST:event_jbtnConfirmarActionPerformed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        Impressora.imprimir(Util.cupom(consulta, TipoImpressao.BEMATHEC_TEXT).toString());
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        //java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela
        String cartao = txtCartao.getText();
        txtDesconto.setText("");
        txtValorRecebido.setText("");

        if ("".equals(cartao)) {
            JOptionPane.showMessageDialog(null, "Deve ser informado um número de cartão.");
        } else {

            String dataTransacao = Util.dateToString(this.getDataTransacaoFinanceira());

            Double desconto = "".equals(txtDesconto.getText()) ? 0.0 : Double.valueOf(txtDesconto.getText().replace(".", "").replace(",", "."));
            Double valorRecebido = "".equals(txtValorRecebido.getText()) ? 0.0 : Double.valueOf(txtValorRecebido.getText().replace(".", "").replace(",", "."));

            consulta = consultaCartao(cartao, dataTransacao, null, desconto, valorRecebido, this.getIdUsuario(), null);

            atualizarValoresTela();

            cupom.setText(Util.cupom(consulta, TipoImpressao.HTML).toString());

            jbtnConfirmar.setEnabled("ok".equals(consulta.getStatus()));
//        jbtnConfirmar.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void atualizarValoresTela() {
        jlblCPF.setText(consulta.getCpf());
        jlblNomeMensalista.setText(consulta.getNomeMensalista());
        jlblValorMensalidade.setText("R$ " + consulta.getValorReceber());
        jlblTroco.setText("R$ " + consulta.getTroco());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmPagamentoMensalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmPagamentoMensalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmPagamentoMensalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPagamentoMensalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JfrmPagamentoMensalista frmMensalista = new JfrmPagamentoMensalista();
                frmMensalista.setLocationRelativeTo(null);
                frmMensalista.setIdUsuario(201);
                frmMensalista.setDataTransacaoFinanceira(new Date());
                frmMensalista.atualizaVisualizacao();
                frmMensalista.txtCartao.setText("00000851141");
                frmMensalista.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane cupom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton jbtnConfirmar;
    private javax.swing.JToggleButton jbtnImprimir;
    private javax.swing.JLabel jlblCPF;
    private javax.swing.JLabel jlblNomeMensalista;
    private javax.swing.JLabel jlblTroco;
    private javax.swing.JLabel jlblValorMensalidade;
    private javax.swing.JTextField txtCartao;
    private javax.swing.JFormattedTextField txtDesconto;
    private javax.swing.JFormattedTextField txtValorRecebido;
    // End of variables declaration//GEN-END:variables

    public Date getDataTransacaoFinanceira() {
        return dataTransacaoFinanceira;
    }

    public void setDataTransacaoFinanceira(Date dataTransacaoFinanceira) {
        this.dataTransacaoFinanceira = dataTransacaoFinanceira;
    }

    public Integer getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public void atualizaVisualizacao() {

    }

    private static RetornoConsultaCartaoVO consultaCartao(java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela, java.lang.Double desconto, java.lang.Double valorRecebido, java.lang.Integer usuarioId, java.lang.String placaCarro) {
        br.com.dynatec.controlador.ws.AcessoControle_Service service = new br.com.dynatec.controlador.ws.AcessoControle_Service(Parametros.WSDL_WEBSERVICE);
        br.com.dynatec.controlador.ws.AcessoControle port = service.getAcessoControlePort();
        return port.consultaCartao(cartao, dataTransasaoFinanceira, codTabela, desconto, valorRecebido, usuarioId, placaCarro);
    }

    private static RetornoConsultaCartaoVO processaCartao(java.lang.String cartao, java.lang.String dataTransasaoFinanceira, java.lang.Integer codTabela, java.lang.Double desconto, java.lang.Double valorRecebido, java.lang.Integer usuarioId, java.lang.String placaCarro) {
        br.com.dynatec.controlador.ws.AcessoControle_Service service = new br.com.dynatec.controlador.ws.AcessoControle_Service(Parametros.WSDL_WEBSERVICE);
        br.com.dynatec.controlador.ws.AcessoControle port = service.getAcessoControlePort();
        return port.processaCartao(cartao, dataTransasaoFinanceira, codTabela, desconto, valorRecebido, usuarioId, placaCarro);
    }

    public RetornoConsultaCartaoVO getConsulta() {
        return consulta;
    }

    public void setConsulta(RetornoConsultaCartaoVO consulta) {
        this.consulta = consulta;
    }

}
